#! /usr/bin/env node
var args = require('args');
var G_LOCK = require('greenlock');
var mkdirp = require('mkdirp');
var fs = require('fs');

args.option(
	'conf', 
	'Path to config file (defaults to /etc/letsencrypt-bot/config.json or ~/.letsencrypt-bot.json)'
);
var opt = args.parse(process.argv);

var config;

try {
	if (opt.conf) {
		config = JSON.parse(fs.readFileSync(opt.conf,'utf8'));
	}
}
catch (e) {
	try {
		config = JSON.parse(fs.readFileSync('/etc/letsencrypt-bot/config.json','utf8'))
	}
	catch (e) {
		try {
			config = JSON.parse(fs.readFileSync('~/.letsencrypt-bot.json','utf8'))
		}
		catch (e) {
			console.error('ERROR: Cannot find config file!');
			process.exit();
		}
	}
}

// var ACME = '/home/wallet/public_html/.well-known/acme-challenge';
// var HOME = './ssl';
// var domains = [ 'wallet.nchain.ir' ];

var ACME = config.acme;
var HOME = config.workdir;
var domains = config.domains;

var store = require('le-store-certbot').create({
		configDir: HOME,
		privkeyPath: ':configDir/ssl.key/:hostname.key',
		fullchainPath: ':configDir/:hostname.full_ca_bundle',
		certPath: ':configDir/ssl.crt/:hostname.crt',
		chainPath: ':configDir/:hostname.ca_bundle',
		webrootPath: ACME,
		debug: false
	});
	
var challenge = require('le-challenge-fs').create({
		webrootPath: ACME,
		loopbackPort: 5001,
		loopbackTimeout: 10000,
		debug: false
	});
	
var greenlock = G_LOCK.create({
		version: 'draft-12',
		server: 'https://acme-v02.api.letsencrypt.org/directory',
		store: store,
		challenges: {
			'http-01': challenge
		},
		challengeType: 'http-01'
	});

mkdirp.sync(HOME + '/ssl.key');
mkdirp.sync(HOME + '/ssl.crt');
greenlock.check({ domains: domains })
	.then(ok => {
		if (ok) return;
		
		greenlock.register({
			domains: domains,
			email: 'amouha@visionsoba.com',
			agreeTos: true,
			rsaKeySize: 2048,
			challengeType: 'http-01'
		})
		.then(() => console.log('success'))
		.catch(err => console.error(err));
	});
	
