#! /usr/bin/env node
var args = require('args');
var G_LOCK = require('greenlock');
var mkdirp = require('mkdirp');
var fs = require('fs');
var os = require('os');

args.option(
	'conf', 
	'Path to config file (defaults to /etc/letsencrypt-bot/config.json or ~/.letsencrypt-bot.json)'
);
var opt = args.parse(process.argv);

var rawconfig = '-';

function die (message) {
	console.error('ERROR: ' + message);
	process.exit();
}

if (opt.conf) {
	try {
		rawconfig = fs.readFileSync(opt.conf,'utf8');
	}
	catch (e) {
		die('Unable to open ' + opt.conf);
	}
}
else {
	try {
		rawconfig = fs.readFileSync('/etc/letsencrypt-bot/config.json','utf8');
	}
	catch (e) {
		console.log('Unable to read global config file, trying local config..');
		try {
			rawconfig = fs.readFileSync(os.homedir() + '/.letsencrypt-bot.json','utf8');
		}
		catch (e) {
			die('Cannot find config file!');
		}
	}
}

var config = JSON.parse(rawconfig);

var ACME = config.acme;
var HOME = config.workdir;
var domains = config.domains;
var email = config.email || 'letsencrypt.bot@mailinator.com';

var store = require('le-store-certbot').create({
		configDir: HOME,
		privkeyPath: ':configDir/ssl.key/:hostname.key',
		fullchainPath: ':configDir/:hostname.full_ca_bundle',
		certPath: ':configDir/ssl.crt/:hostname.crt',
		chainPath: ':configDir/:hostname.ca_bundle',
		webrootPath: ACME,
		debug: false
	});
	
var challenge = require('le-challenge-fs').create({
		webrootPath: ACME,
		loopbackPort: 5001,
		loopbackTimeout: 10000,
		debug: false
	});
	
var greenlock = G_LOCK.create({
		version: 'draft-12',
		server: 'https://acme-v02.api.letsencrypt.org/directory',
		store: store,
		challenges: {
			'http-01': challenge
		},
		challengeType: 'http-01'
	});

mkdirp.sync(HOME + '/ssl.key');
mkdirp.sync(HOME + '/ssl.crt');

function checkDomains (allDomains) {
	if (!allDomains.length) return;
	
	var domain = allDomains.shift();
	
	greenlock.check({ domains: [ domain ] })
		.then(ok => {
			if (ok) {
				console.log(domain + ' is still fresh');
				return checkDomains(allDomains);
			}
			
			greenlock.register({
				domains: [ domain ],
				email: email,
				agreeTos: true,
				rsaKeySize: 2048,
				challengeType: 'http-01'
			})
			.then(() => {
				console.log(domain + ' successfully registered');
				checkDomains(allDomains);
			})
			.catch(err => console.error(err));
		});
		
}

checkDomains(domains);